import os

_ = os.getenv

DB_HOST = _('DB_HOST')
DB_USER = _('POSTGRES_USER')
DB_PASSWORD = _('POSTGRES_PASSWORD')
DB_NAME =_('POSTGRES_DB')
SECRET_KEY = _('SECRET_KEY', 'my_precious')
DEFAULT_ROUNDS = int(_('DEFAULT_ROUNDS', '15'))
ACCESS_TOKEN_KEY = _('ACCESS_TOKEN_KEY', '')
REFRESH_ACCESS_TOKEN_KEY = _('REFRESH_ACCESS_TOKEN_KEY', '')
