version: '3.8'

services:

  web:
    image: web
    build:
      context: .
      dockerfile: web/Dockerfile
    working_dir: /app/web
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-superuser}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  pgadmin:
    image: dpage/pgadmin4
    links:
      - db
    volumes:
      - type: volume
        source: pgadmin-data
        target: /var/lib/pgadmin
    ports:
      - ${PGADMIN_LISTEN_PORT:-5050}:5050
    env_file:
      - .env
    environment:
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT:-5050}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@project.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - db

volumes:
  pgadmin-data:
